### ISSUE TITLE
Документация по API

### ISSUE THREAD

**Issue by panferovaleksey** [volshebniks/sauresha#1]
У вас наверняка есть какая-то документация по API. Официальная или в виде Swagger или что-то подобное. Нельзя ли и ее выложить сюда? По старому API и по новому?

**Comment by volshebniks** [comment]
Добрый день!

Саму документацию по API, можно запросить в поддержке Saures. Они пришлют по запросу.
Раз ее нет совсем в открытом доступе - я тоже не буду этого делать.

Но если интересно могу выложить проект для Postman с реализацией двух версий API  :)

**Comment by panferovaleksey** [comment]
Да. Проект Postman был бы не лишним :) Спасибо.

**Comment by volshebniks** [comment]
Вот :  [postman ](https://cloud.g-s-a.me/index.php/s/T7ATisZda6TskWd)

**Comment by volshebniks** [comment]
вот: [postman ](https://cloud.g-s-a.me/index.php/s/T7ATisZda6TskWd)
