### ISSUE TITLE
Проблемы во время загрузки HA начиная с версии 0.3.5

### ISSUE THREAD

**Issue by avbor** [volshebniks/sauresha#2]
Начиная с версии 0.3.5 (в вплоть до 0.3.7) при загрузке HA появляется большое кол-во ошибок в других компонентах:
![image](https://user-images.githubusercontent.com/32452033/73740442-4431d780-4759-11ea-9e7a-e5fde1011403.png)
Если откатиться на 0.2.3 все эти ошибки магических образом пропадают.
Где-то что-то пошло не так... =)

**Comment by volshebniks** [comment]
Добрый день!
Правильно я понимаю, что всё работает корректно? - но в лог ошибки сыпятся ... причем от других о компонентов?

**Comment by avbor** [comment]
Я честно говоря не проверял полноценную работу, установил - посмотрел на кол-во ошибок - откатился.
Как то мне не уютно жыть с таким кол-ом ошибок =)

**Comment by volshebniks** [comment]
я потестировал. на работе вообще никак не сказывается.
Это же не ошибки  - warning
Но я разберусь.

**Comment by volshebniks** [comment]
@avbor  Попробуйте версию 0.3.8 - вернул синхронные вызовы. - Должно помочь.

Буду разбираться дальше не торопясь.

**Comment by avbor** [comment]
Поставил 0.3.8, масса ворнингов ушал, но остался ворнинг на сам sauresha:
![image](https://user-images.githubusercontent.com/32452033/73753517-e494f580-4773-11ea-8847-ac8d1c4d43b7.png)
На ветке 0.2.* такого не было =)

В любом случае это все не горит, спасибо за компонент!

**Comment by volshebniks** [comment]
да с ошибкой по медленому обновлению самого компонента  мне все понятно. 
В  версиях 0.3 используется их новое API.  В 0.2 старое. Поддрежка Saures крайне рекомендовала использовать новое ... старое скоро отключат. А сервера с новым API у них тормозят.
