### ISSUE TITLE
Баг обработки логина при настройке через GUI

### ISSUE THREAD

**Issue by Gimlir** [volshebniks/sauresha#27]
при попытке использовать адрес почты (логин) вида хххх@yyyy.name при настройке через GUI получаю ошибку 
![image](https://user-images.githubusercontent.com/39776670/171405905-0002c471-caa5-4af4-81e1-d797a246e7dd.png)
в логах
```
2022-06-01 15:27:59 ERROR (MainThread) [homeassistant.setup] Error during setup of component sauresha
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/setup.py", line 235, in _async_setup_component
result = await task
File "/config/custom_components/sauresha/__init__.py", line 39, in async_setup
yaml_email: str = user_cfg[CONF_EMAIL]
KeyError: 'email'
```
при этом использование адреса почты вида хххх@gmail.com к такой ошибке не приводит, конфигурация сохраняется нормально и интеграция загружается в НА нормально. В логах вижу, что интеграция успешно пытается в этим логином авторизоваться по АПИ ([custom_components.sauresha.api] Неправильный email или пароль).

Поправьте, плиз, валидацию адреса email. Часто встречаю такой кейс, когда домен первого уровня длиннее  3 символов не проходит проверки всяческими регулярками.

**Comment by volshebniks** [comment]
> при попытке использовать адрес почты (логин) вида хххх@yyyy.name при настройке через GUI получаю ошибку ![image](https://user-images.githubusercontent.com/39776670/171405905-0002c471-caa5-4af4-81e1-d797a246e7dd.png) в логах
> 
> ```
> 2022-06-01 15:27:59 ERROR (MainThread) [homeassistant.setup] Error during setup of component sauresha
> Traceback (most recent call last):
> File "/usr/src/homeassistant/homeassistant/setup.py", line 235, in _async_setup_component
> result = await task
> File "/config/custom_components/sauresha/__init__.py", line 39, in async_setup
> yaml_email: str = user_cfg[CONF_EMAIL]
> KeyError: 'email'
> ```
> 
> при этом использование адреса почты вида хххх@gmail.com к такой ошибке не приводит, конфигурация сохраняется нормально и интеграция загружается в НА нормально. В логах вижу, что интеграция успешно пытается в этим логином авторизоваться по АПИ ([custom_components.sauresha.api] Неправильный email или пароль).
> 
> Поправьте, плиз, валидацию адреса email. Часто встречаю такой кейс, когда домен первого уровня длиннее 3 символов не проходит проверки всяческими регулярками.

а у вас случайно с configuration.yaml нет настроек?  попробуйте удалить.

**Comment by Gimlir** [comment]
Были закоментированные, сейчас удалил совсем. Разницы нет, ни при перезапуске, ни при удалении интеграции и установке снова.
При этом, похоже на то, что логин и пароль все же успешно используются, т.к. даже в интеграции отмеченной как не запустившаяся в настройках вижна полученная по апи квартира
![image](https://user-images.githubusercontent.com/39776670/171421554-484f394a-6c64-4623-aeb2-c20a1dfa9e89.png)

**Comment by volshebniks** [comment]
я кажется понял в чем было дело. если не сложно обновите еще раз из ветки master

**Comment by Gimlir** [comment]
Переустановил через HACS путем полного удаления и установки с чистого листа из ветки master. 
Интеграция запустилась, есть баги, но  уже другие, проблема этого issue решена.
