### ISSUE TITLE
Error doing job: Task exception was never retrieved

### ISSUE THREAD

**Issue by avbor** [volshebniks/sauresha#3]
И снова не все гладко в королевстве =)
Совершенно неожиданно лог стал заваливаться однотипными сообщениями:
![image](https://user-images.githubusercontent.com/32452033/73943267-8433be80-4901-11ea-857f-b7542938c60f.png)
Спустя пару минут после перезагрузка HA:
![image](https://user-images.githubusercontent.com/32452033/73943315-99a8e880-4901-11ea-8565-9814d0dfef3a.png)

Возможно что то поломалось на стороне API сауреса, но было б, наверное, хорошо как то это отлавливать =)

**Comment by volshebniks** [comment]
повторить не смог, но судя по логу что то пошло не так в процессе получения нового  статуса.
API и правда бывает отваливается временно.
поправил чуть чуть код (версия 0.3.9).

**Comment by avbor** [comment]
Да, вчера вечером оно само как то рассосалось, версию обновил посмотрим как будет жить.

**Comment by Galdus** [comment]
Добрый вечер. Вчера обрадовался наличию такой интеграции, поставил, настроил. 
А сегодня с утра вац, паламалося.....
![02](https://user-images.githubusercontent.com/64501938/81224604-a2888380-8ff0-11ea-98c3-ae7ac82f0fad.PNG)
![01](https://user-images.githubusercontent.com/64501938/81224613-a61c0a80-8ff0-11ea-8c7c-577e3e4aac8a.PNG)
Подскажите как починить?

**Comment by avbor** [comment]
Да, что-то пошло не так:
![image](https://user-images.githubusercontent.com/32452033/81263489-6ed94800-9048-11ea-9211-2795a9aae5fe.png)
Еще вчера все нормально работало, изменения на стороне сауруса?

**Comment by volshebniks** [comment]
Да похоже или отвалилось API или изменились адреса на стороне Saures.

Написал им в поддержку. Как ответят починю.

**Comment by volshebniks** [comment]
Выложена версия 0.4.0 - использует новое Saures API, тестировал только на счетчика воды.
Просьба при нахождении ошибок создавать новые issue
