### ISSUE TITLE
Сменить тип устройства на binary sensor для каналов типа "Состояние крана"

### ISSUE THREAD

**Issue by Gimlir** [volshebniks/sauresha#30]
![image](https://user-images.githubusercontent.com/39776670/171841246-2241dd81-d037-4b5b-93dc-b04729313013.png)
Для такого вида канала, получаемого с контроллера Саурес и его данных Закрыто\Открыто больше подходит binary sensor.
Сейчас Открыто = 0, предлагаю сконвертировать в binary sensor c device class opening: on means open, off means closed (https://www.home-assistant.io/integrations/binary_sensor/)

**Comment by volshebniks** [comment]
да я в общем уже так сделал, но остался вопрос - кроме самого статуса, у данного типа есть еще Condition, если он = "Ошибок нет", то всё понятно, но он может быть = "Обрыв" -  если сделать этот тип устройств сенсором - то я могу писать в состояние - обрыв, а если это бинарный сенсор - то это будет видно  только в атрибутах. 
если так OK - то сделаю бинарным сенсором.

**Comment by Gimlir** [comment]
На мой взгляд, да, лучше перевести в бинарные сенсоры с атрибутом Condition

**Comment by volshebniks** [comment]
сделал в ветке master

**Comment by Gimlir** [comment]
Работает! Спасибо!
