### ISSUE TITLE
Не появляется в интеграциях в GUI

### ISSUE THREAD

**Issue by eliahru** [volshebniks/sauresha#33]
После установки через HACS компонент виден в нем, но отсутствует в списке кнопки "добавить" в интеграциях. 
Пробовал версии 0.6.5 и 1.0.0 - результат одинаков. 
HASS, разумеется, перезапускал. 
Ошибок в логе нет. 
HASS 2022.6.2

**Comment by volshebniks** [comment]
в GUI появляется только версися 1.0.0 из ветки master
![image](https://user-images.githubusercontent.com/2587548/172219950-6d7a0d62-d3a1-432e-a8bb-0dd3b6c214e9.png)

**Comment by Gimlir** [comment]
Устанавливайте в HACS  версию Master
![image](https://user-images.githubusercontent.com/39776670/172323470-43292cb9-e947-44cd-bf7c-2b9599ddcd62.png)
Если после перезапуска в поиске не находит интеграцию - перезагрузите страницу с очисткой кэша (Ctrl+F5)
