### ISSUE TITLE
После обновления 0.4.0

### ISSUE THREAD

**Issue by Galdus** [volshebniks/sauresha#4]
По счетчикам воды все заработало, электричество не показывает.
Это единственное что в логах нашел:
![03](https://user-images.githubusercontent.com/64501938/81281473-8d4c3d00-9062-11ea-88f2-321801279e99.PNG)
Атрибуты старые, еще позавчерашние.
![04](https://user-images.githubusercontent.com/64501938/81281974-3dba4100-9063-11ea-9696-e1463b04e925.PNG)

**Comment by volshebniks** [comment]
выложил 0.4.1  - в статус выводятся все значения из многотарифного счетчика.
Сделать как было раньше нельзя - удалили поле из API с сумарным потреблением.

**Comment by Galdus** [comment]
Ага, работает, благодарю
