### ISSUE TITLE
Перестал обновляться контроллер в НА

### ISSUE THREAD

**Issue by vsimanin** [volshebniks/sauresha#42]
Автоматизация перестала работать на 2022.9.*
Последнее успешное соединение до обновления НА - 11.09.22
В настройках обновление каждые 120 минут. Сам контроллер на сервер данные 100% шлет, скрин прикладываю.

Эта ошибка возникла в кастомной интеграции.

Logger: homeassistant
Source: custom_components/sauresha/sauresha.py:105
Integration: sauresha (documentation)
First occurred: 13 сентября 2022 г., 23:26:56 (6 occurrences)
Last logged: 09:26:56

Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/concurrent/futures/thread.py", line 58, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/sauresha/sensor.py", line 306, in refresh
    self.update()
  File "/config/custom_components/sauresha/sensor.py", line 352, in update
    self._state = self.fetch_state()
  File "/config/custom_components/sauresha/sensor.py", line 320, in fetch_state
    my_controller = self.current_controller_info
  File "/config/custom_components/sauresha/sensor.py", line 274, in current_controller_info
    return self.controller.get_controller(self.flat_id, self.serial_number)
  File "/config/custom_components/sauresha/sauresha.py", line 113, in get_controller
    controllers = self.get_controllers(flat_id)
  File "/config/custom_components/sauresha/sauresha.py", line 105, in get_controllers
    self._sensors = controllers
UnboundLocalError: local variable 'controllers' referenced before assignment

![Screenshot_20220913-224645](https://user-images.githubusercontent.com/9263449/190080219-17f2c976-0e2a-405c-a9c3-0a02f8a3368e.jpg)
![Screenshot_20220913-224135__01](https://user-images.githubusercontent.com/9263449/190080227-fe913934-1262-4527-94a0-89e3bc9266e1.jpg)

**Comment by volshebniks** [comment]
попробуйте устновить верисиз из master ветки.
настройка полностью через GUI, код значительно другой.

**Comment by vsimanin** [comment]
> попробуйте устновить верисиз из master ветки. настройка полностью через GUI, код значительно другой.

Установил, но обнаружил проблему - не могу избавиться от старых сенсоров. Они не удаляются.
![Screenshot_20220924-213453](https://user-images.githubusercontent.com/9263449/192113555-fc3ccb22-5932-4ede-86db-904bd66cd3e1.jpg)

**Comment by vsimanin** [comment]
> попробуйте устновить верисиз из master ветки. настройка полностью через GUI, код значительно другой.

Спасибо, это помогло. Подскажите, как отключить дебаг? В логи пишется слишком много лишнего для простого обывателя.

**Comment by volshebniks** [comment]
> > попробуйте устновить верисиз из master ветки. настройка полностью через GUI, код значительно другой.
> 
> Спасибо, это помогло. Подскажите, как отключить дебаг? В логи пишется слишком много лишнего для простого обывателя.

в файле const.py есть строка: CONF_ISDEBUG: Boolean = True
соответвенно заменить True на False.

Или немного подождать - я планирую все же зарелизить master ветку.  Там изначально отключу.

**Comment by vsimanin** [comment]
На версии с master (1.0?) перестал обновляться контроллер в конце октября. Обновляется ровно один раз - при старте НА, далее показания не меняются. 

Сейчас вышли апдейты для 0.6.
Я уже запутался какую версию ставить?) 1.0 удобнее в настройке, но сейчас не работает.  Что посоветуете?

**Comment by volshebniks** [comment]
Обвноляться будет только версия из ветки master. Я посмотрю, что с ней. 
Ошибки в логе есть?

**Comment by vsimanin** [comment]
> Обвноляться будет только версия из ветки master. Я посмотрю, что с ней. Ошибки в логе есть?

Нет, в логе пусто. Возможно это связано с тем, что я выставил CONF_ISDEBUG в false.

И ещё вопрос. Как узнавать об обновах в master? HACS упорно предлагает поставить обновление версии 0.6.5, говорит, что моя версия из master не актуальна.

**Comment by volshebniks** [comment]
в ближайшие дни потестирую верисю в ветке master и сделаю из нее релиз. после этого всё будет обновляться стандартно.

**Comment by vsimanin** [comment]
> в ближайшие дни потестирую верисю в ветке master и сделаю из нее релиз. после этого всё будет обновляться стандартно.

Хорошо. Спасибо.
Продолжаю наблюдения за версией master:
1. В устройствах, если у данной интеграции нажать кнопку НАСТРОИТЬ, то появится окно, где можно выбрать квартиру(объект). По умолчанию галка не установлена. Поставил, но не понял на что это влияет 
2. Отсутствует возможность изменить время опроса в минутах после первичного добавления интеграции.
3. Вернул дебаг, перезагрузил НА. Через несколько минут в логах повилась ошибка:
Эта ошибка возникла в кастомной интеграции.

Logger: custom_components.sauresha.api
Source: custom_components/sauresha/api.py:314
Integration: SauresHA (documentation, issues)
First occurred: 22:13:53 (3 occurrences)
Last logged: 22:53:53

'sensors'

**Comment by volshebniks** [comment]
1. По умочланию  - делается запрос на все имеющиеся квартиры. Устновка этого чекбокса уменьшает количество запросов к API и как следствие возможность блокировки.
2.  да упустил этот момент. но можно удалить, а затем снова добавить интеграцию.
3.  посмотрю. 

Спасибо!

**Comment by vsimanin** [comment]
Добрый день! Обновился до последней версии, полностью перезагружал сервер, но все тщетно. Сенсор контроллера обновляется лишь однажды - при первом запуске интеграции после старта НА. Никаких ошибок в логе нет. Помогите, прошу:(

На скринах видно даты, а так же кол-во обращений к серверу: 607 vs 606:
![Screenshot_2022-11-14-09-09-17-81_ec6b81f233f27601c4292aaa765b3790](https://user-images.githubusercontent.com/9263449/201588330-2c544e79-2750-44c8-8c6b-a8cc6b889606.jpg)
![Screenshot_2022-11-14-09-10-19-76_c3a231c25ed346e59462e84656a70e50](https://user-images.githubusercontent.com/9263449/201588339-76ead93b-b965-47b2-b237-4ebc91a94ebc.jpg)

В интеграции опрос каждые 120 минут, галочка на квартире стоит(объект всего один)

**Comment by volshebniks** [comment]
Я проверил. у меня обновляется корректно.
Могу вам посоветовать попробовать выполнить следущие шаги.
1. Удалить папку sauresha из custom_components.
2. Удалить все настройки какие были сделаны ранее и через GUI и особеннно через YAML
3. Обновить Home Assistant, если давно этого не делали.
4. Установить мой компонент

Если не поможет - добавлю логирования в след.версии. во все места где даже в тории может упасть.

**Comment by vsimanin** [comment]
> Если не поможет - добавлю логирования в след.версии. во все места где даже в тории может упасть.

Полностью снес и перезагрузил НА. Поставил. Пока 2 дня полет нормальный. 
Из отличий, после добавления интеграции не стал ставить галочку на объект в настройках.
