### ISSUE TITLE
Как добавить сенсор в HA?

### ISSUE THREAD

**Issue by AFrolov203** [volshebniks/sauresha#44]
Добрый день!
Спасибо за Вашу работу, но никак не могу добавить сенсор в HA. Я начинающий пользователь, не могли бы Вы расписать более подробно тот процесс?

**Comment by AFrolov203** [comment]
Можете расписать этот пункт:
"Настройте sauresha sensor и/или binary_sensor."?
Буду очень признателен

**Comment by volshebniks** [comment]
Поставьте версию из master ветки. там всё настривается из GUI.

**Comment by AFrolov203** [comment]
> Поставьте версию из master ветки. там всё настривается из GUI.

Спасибо! 

Установил версию master. В каком пункте меню GUI HA выбираются и настраиваются датчики протечки (так и не смог найти)?

Заранее спасибо за ответ.

Прошу прощения за глупые вопросы, пока новичек в Home Assistant

**Comment by volshebniks** [comment]
в найстройках -  в устроствах и службах - добавляете интеграцию Saures, вводите что спросит. сенсоры на датчики создадутся сами.  Но если честно полгаться в случае протечки на эти сенсоры я бы не стал ... так как опрос сервера происходит со значительным таймаутом и в случае протечки это может быть критично.

**Comment by AFrolov203** [comment]
> в найстройках - в устроствах и службах - добавляете интеграцию Saures, вводите что спросит. сенсоры на датчики создадутся сами. Но если честно полгаться в случае протечки на эти сенсоры я бы не стал ... так как опрос сервера происходит со значительным таймаутом и в случае протечки это может быть критично.

Спасибо за оперативный ответ. Но как появится в HA интеграция Saures, если установка была через HACS? При поиске интеграций, Saures нет в списке. Или я не туда смотрю?

![2022-09-30_19-00-03](https://user-images.githubusercontent.com/113948865/193311072-4b9cd703-94b2-44a8-bbd3-982d4ac7c38d.png)

**Comment by volshebniks** [comment]
интеграци и ставится через HACS. Смотрите вы похоже туда. Но если её тут нет,, значит у вас стоит обычная версия 0.6.5
А через GIU настраивается только версия из ветки master

**Comment by AFrolov203** [comment]
> интеграци и ставится через HACS. Смотрите вы похоже туда. Но если её тут нет,, значит у вас стоит обычная версия 0.6.5 А через GIU настраивается только версия из ветки master

Спасибо. Все получилось. Правда переустанавливал все кучу раз. Что именно помогло так и не выяснил. Но все работает)
