### ISSUE TITLE
Добавить заряд батареи контроллера и WiFi сигнал.

### ISSUE THREAD

**Issue by FullSilence** [volshebniks/sauresha#47]
САБЖ

**Comment by volshebniks** [comment]
так есть же
![image](https://user-images.githubusercontent.com/2587548/208383582-eb269b38-58ba-45d7-96e9-f8b38ee40b97.png)

**Comment by FullSilence** [comment]
> так есть же ![image](https://user-images.githubusercontent.com/2587548/208383582-eb269b38-58ba-45d7-96e9-f8b38ee40b97.png)
И правда, извиняюсь, недоглядел.

![image](https://user-images.githubusercontent.com/16937393/208425067-ec304ea4-7bc5-44e0-82fc-71c3ef3b9065.png)
А как их добавить в lovelace? Нужно создать свой сенсор?

**Comment by volshebniks** [comment]
да конечно.
