### ISSUE TITLE
Не обновляются данные

### ISSUE THREAD

**Issue by Galdus** [volshebniks/sauresha#5]
Добрый день,

Вчера перестали приходить данные на сенсоры.

**Comment by volshebniks** [comment]
> Вчера перестали приходить данные на сенсоры.

Добрый день!.

Какая версия HA используется?

**Comment by Galdus** [comment]
You are currently running version 0.115.2

**Comment by volshebniks** [comment]
Спасибо! Как оказалось не важно.

Лежит API на стороне Saures.   Даже просто авторизация не проходит.
Написал им в поддержку.  Может объяснят причины.

**Comment by volshebniks** [comment]
Пишут: _Да, потому что очень много стало совершенно ненужных частых запросов, вплоть до обращений к серверу в бесконечном цикле без каких-либо задержек.  Рекомендуем обращаться не чаще чем раз в час. Скоро доделаем банлист и не просто запросы будут пропускаться, а сервер будет блокировать часто обращающихся минимум на сутки._

Но судя по всем работает у них это сейчас пипец как криво :( - меня банит просто за три запроса. Авторизация  и два запроса по счетчикам.   Пытаюсь это до них донести.

**Comment by volshebniks** [comment]
Обновите до 0.5.0 - Существенно уменьшено кол-во обращений к серверу Saures. Должно помочь с блокировками с их стороны.

Рекомендую в настройках указать
scan_interval:
    minutes: 60
Иначе могут быть блокировки в будущем. - Так сообщила их поддержка

**Comment by avbor** [comment]
На версии 0.5 все так же - API ERROR during Auth process
Оно со временем само разбаниться или надо поддержку попинать?
И еще вопрос - scan_interval только для обычных сенсоров надо указать или для бинарных тоже?

**Comment by volshebniks** [comment]
Должно разбанится само.  Есть подозрение, что про бинарные сенсоры никто не подумал. - Они  обновляются очень часто. 

Нужно  тестировать.

**Comment by avbor** [comment]
Ага... и если от этого придется отказаться будет совсем бида, у меня через бинарник прилетает событие сработки системы защиты от протечек, так себе будет если событие будет прилетать через час =)

**Comment by andysaab** [comment]
> Ага... и если от этого придется отказаться будет совсем бида, у меня через бинарник прилетает событие сработки системы защиты от протечек, так себе будет если событие будет прилетать через час =)

Ага, вообще жесть :( 
Таким образом они на свое приложение с пушапами подсаживают.
Вообщем, вот тут доходчиво расписано - https://www.saures.ru/o-sisteme/prices/

**Comment by avbor** [comment]
Черт, и правда:

![image](https://user-images.githubusercontent.com/32452033/94802240-f5276980-03ef-11eb-8960-570d37ee8b21.png)

**Comment by volshebniks** [comment]
В общем в данное время, у меня сенсоры обновляются корректно.  - Настроил на 1 раз в час, но в приницпе и раз в 15 минут должно пока работать. 

Для счетчиков воды, электирчества это в общем допустимо.  Для датчиков протечки (бинарные сенсоры) - Полная жесть.  :((

**Comment by andysaab** [comment]
> В общем в данное время, у меня сенсоры обновляются корректно. - Настроил на 1 раз в час, но в приницпе и раз в 15 минут должно пока работать.
> 
> Для счетчиков воды, электирчества это в общем допустимо. Для датчиков протечки (бинарные сенсоры) - Полная жесть. :((
У меня тоже стояло 15 минут. После апдейта на 0.5 данные появились, но потом прилетело обновление ХА и после пары ребутов данных опять нет, забанили, похоже. Выставил опрос на 60 минут, жду теперь разбана.

Upd
Ну вот, точно! Через час появились данные.

**Comment by avbor** [comment]
Поставил scan_interval в 60 мин для обоих типов сенсоров, посмотрим разбанит ли...

**Comment by volshebniks** [comment]
как оказалось scan_interval по умолчанию в binary_sensors  не использовался.
Добавил его туда в версии 0.5.1. Может поможет.

**Comment by avbor** [comment]
Пока чет не очень...
![image](https://user-images.githubusercontent.com/32452033/94826421-f8325200-040f-11eb-886f-f6c7065a4162.png)

**Comment by andysaab** [comment]
С сегодняшнего утра в лог началось валиться следующее:
2020-10-06 00:11:18 ERROR (MainThread) [homeassistant] Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/sauresha/sensor.py", line 119, in refresh
    self.update()
  File "/config/custom_components/sauresha/sensor.py", line 209, in update
    self._state = self.fetch_state()
  File "/config/custom_components/sauresha/sensor.py", line 161, in fetch_state
    meter = self.current_meter
  File "/config/custom_components/sauresha/sensor.py", line 130, in current_meter
    return self.controller.get_meter(self.flat_id, self.serial_number)
  File "/config/custom_components/sauresha/sauresha.py", line 97, in get_meter
    meters = self.get_meters(flat_id)
  File "/config/custom_components/sauresha/sauresha.py", line 75, in get_meters
    sensors = self.__session.get(f'https://api.saures.ru/1.0/object/meters', params={
KeyError: 'sensors'
Повторяется ровно через час, как и стоит опрос контроллера.
До сегодняшнего числа подобного не было.
Данные принимаются, показания и статус контроллера в норме.
Опять API подкрутили?

**Comment by avbor** [comment]
> С сегодняшнего утра в лог началось валиться следующее:

+1 такая же ошибка...

**Comment by volshebniks** [comment]
разбираюсь.  в ошибку в логе вижу.

**Comment by volshebniks** [comment]
в версии 0.5.2  не должно быть данных ошибок в логе.

**Comment by andysaab** [comment]
> в версии 0.5.2 не должно быть данных ошибок в логе.
Всё чистенько стало, спасибо!
