### ISSUE TITLE
планируется ли обновление интеграции под актуальную версию HA?

### ISSUE THREAD

**Issue by oksibutch** [volshebniks/sauresha#50]
Уважаемый автор, планируется ли обновление интеграции под актуальную версию HA?
возможно ли это в ближайшей перспективе? или нужно искать альтернативные варианты интеграции в УД?

PS очень хочется надеятся на то что вы сможете адаптировать ваш плагин под новую версию. Спасибо за ваш труд

**Comment by volshebniks** [comment]
Я перестал пользоваться устройством уже давно.  УК в доме где я живу сама передает все данные куда надо.
Последняя версия HA на которой я проверял последнее обновление  -  2023.5.2  - вполне актуальная.
А что есть проблемы?

**Comment by oksibutch** [comment]
Да не работает уже больше 2х месяцев. 

Ошибка вот
Logger: homeassistant.config_entries
Source: custom_components/sauresha/__init__.py:96
Integration: SauresHA (documentation, issues)
First occurred: 12 июня 2023 г. в 19:59:48 (1 occurrences)
Last logged: 12 июня 2023 г. в 19:59:48

Error setting up entry myemail@mymail.com for sauresha

Traceback (most recent call last):
 File "/usr/src/homeassistant/homeassistant/config_entries.py", line
387, in async_setup
   result = await component.async_setup_entry(hass, self)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
 File "/config/custom_components/sauresha/__init__.py", line 96, in
async_setup_entry
   hass.config_entries.async_setup_platforms(config_entry, PLATFORMS)
   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'ConfigEntries' object has no attribute 'async_setup_platforms'

**Comment by oksibutch** [comment]
Проблема кажется вот в этом
https://github.com/volshebniks/sauresha/issues/48#issuecomment-1536216864

**Comment by baradetsky** [comment]
> Я перестал пользоваться устройством уже давно. УК в доме где я живу сама передает все данные куда надо. Последняя версия HA на которой я проверял последнее обновление - 2023.5.2 - вполне актуальная. А что есть проблемы?

а не пробовали связаться с Saures чтобы передать им наработки по интеграции? может они продолжат поддержку? вы не будете против?

**Comment by dvclever** [comment]
Интеграция перестала работать после обновления на
Home Assistant 2023.7.3
Supervisor 2023.07.1
Operating System 10.3

Проверял на 3х разных серверах и аккаунтах. После переустановки подтягивает квартиру,но датчики воды не прилетают в НА.

**Comment by volshebniks** [comment]
> Интеграция перестала работать после обновления на Home Assistant 2023.7.3 Supervisor 2023.07.1 Operating System 10.3
> 
> Проверял на 3х разных серверах и аккаунтах. После переустановки подтягивает квартиру,но датчики воды не прилетают в НА.

А в логе  ошибки есть?

**Comment by baradetsky** [comment]
ошибки есть, та же история

Logger: custom_components.sauresha.api
Source: custom_components/sauresha/api.py:309
Integration: SauresHA (documentation, issues)
First occurred: 21:40:24 (1 occurrences)
Last logged: 21:40:24

[Errno 104] Connection reset by peer

**Comment by volshebniks** [comment]
работает в доступной последней версии

**Comment by baradetsky** [comment]
увы опять нет... версия 1.0.3 не рабочая(
