### ISSUE TITLE
Работа с контроллером версии 8

### ISSUE THREAD

**Issue by skv-pa** [volshebniks/sauresha#52]
Для работы с новыми NB IoT контроллерами версии 8, в api.py надо добавить:

def get_controller_name(self, version_id):
        return {
            version_id == "1.3"
            or version_id == "1.4"
            or version_id == "1.5": "счетчик C1",
            version_id == "3.1" or version_id == "3.2": "контроллер R1(до 2017)",
            version_id == "3.4": "контроллер R1 8 (2017-2018)",
            version_id == "3.5": "контроллер R1 4 (после 2018))",
            version_id == "4.0": "контроллер R2",
            version_id == "4.1": "контроллер R4",
            version_id == "6.3": "контроллер R5",
            version_id == "7.2": "контроллер R6",
            version_id == "8.2": "контроллер R7(до 2020)",
            version_id == "8.3": "контроллер R7(после 2020)",
            **version_id == "9.1": "контроллер R8(после 2022)",**
        }[True]

**Comment by volshebniks** [comment]
добавил
