### ISSUE TITLE
Объединить показания двух-зонного счетчика э/э

### ISSUE THREAD

**Issue by anikin-ab** [volshebniks/sauresha#56]
стоит счетчик с разделением Т1 Т2 - день/ночь меня по умолчанию
+ общее показание

1) ВОПРОС 
подскажите, как объединить показатель, чтобы в НА только общий расход э/э показывал?
я в прошлый раз делал, по-моему в классе объединял показания (плюсовал), сейчас что-то не пойму, где этот параметр

вот тут надо заменить?

        if len(self.values) == 2:
            self.value = "{0}/{1}".format(self.values[0], self.values[1])
            self.t1 = self.values[0] + self.values[1]
            self.t2 = "-"
            self.t3 = "-"
            self.t4 = "-"

код оригинальный:

class SauresSensor:
    def __init__(self, data):
        self.data = data
        self.name = data.get("meter_name")
        self.type_number = data.get("type", {}).get("number")
        self.type = data.get("type", {}).get("name")
        self.state = data.get("state", {}).get("name")
        self.sn = data.get("sn")
        self.value = data.get("value")
        self.meter_id = data.get("meter_id")
        self.input = data.get("input")
        self.approve_dt = data.get("approve_dt")

        self.values = data.get("vals", [])

        if len(self.values) == 2:
            self.value = "{0}/{1}".format(self.values[0], self.values[1])
            self.t1 = self.values[0]
            self.t2 = self.values[1]
            self.t3 = "-"
            self.t4 = "-"
        elif len(self.values) == 3:
            self.value = "{0}/{1}/{2}".format(
                self.values[0], self.values[1], self.values[2]
            )
            self.t1 = self.values[0]
            self.t2 = self.values[1]
            self.t3 = self.values[2]
            self.t4 = "-" 

2) еще ВОПРОС
и подскажите, в каком разделе период обновления датчиков задается?

**Comment by sweethome29** [comment]
> 2. еще ВОПРОС
>    и подскажите, в каком разделе период обновления датчиков задается?

![IMG_20231022_090857](https://github.com/volshebniks/sauresha/assets/113246384/baa808b0-a5ed-47c1-ad04-db01b8000e6e)

**Comment by anikin-ab** [comment]
сам отвечу)) 
заходим в classes.py


строка 45
if len(self.values) == 2:
            self.value = self.values[0] + self.values[1]
            self.t1 = self.values[0] + self.values[1]
            self.t2 = "-"
            self.t3 = "-"
            self.t4 = "-"
        # БЫЛО ВОТ ТАК    
        # if len(self.values) == 2:
        #     self.value = "{0}/{1}".format(self.values[0], self.values[1])
        #     self.t1 = self.values[0]
        #     self.t2 = self.values[1]
        #     self.t3 = "-"
        #     self.t4 = "-"
