### ISSUE TITLE
Обрыв датчика

### ISSUE THREAD

**Issue by free-emotion** [volshebniks/sauresha#7]
Приветствую. Предложу небольшое улучшение.

Кроме состояний "Ошибок нет" и "Протечка", в бинарных датчиках присутствует третье состояние: "Обрыв".

Правильнее в таком случае переводить значение датчика в True, чтобы привлечь внимание к неисправности.
<img width="291" alt="obryv" src="https://user-images.githubusercontent.com/61333302/98971692-8d9e2700-2522-11eb-9eff-9daf55b0b5d2.png">
.

**Comment by volshebniks** [comment]
добавил в версию 0.5.3
