### ISSUE TITLE
Не обновляется сенсор электросчетчика

### ISSUE THREAD

**Issue by Kirilloff73** [volshebniks/sauresha#8]
Поставил Ваш компонент SauresHA, сенсор электросчетчика появился, но обновляется только при перезагрузке сервера НА.  
В логах появилась вот такая ошибка: 
Logger: homeassistant
Source: custom_components/sauresha/sauresha.py:101
First occurred: 11:42:58 (1 occurrences)
Last logged: 11:42:58

Error doing job: Future exception was never retrieved
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/concurrent/futures/thread.py", line 57, in run
    result = self.fn(*self.args, **self.kwargs)
  File "/config/custom_components/sauresha/sensor.py", line 258, in refresh
    self.update()
  File "/config/custom_components/sauresha/sensor.py", line 304, in update
    self._state = self.fetch_state()
  File "/config/custom_components/sauresha/sensor.py", line 272, in fetch_state
    my_controller = self.current_controller_info
  File "/config/custom_components/sauresha/sensor.py", line 230, in current_controller_info
    return self.controller.get_controller(self.flat_id, self.serial_number)
  File "/config/custom_components/sauresha/sauresha.py", line 109, in get_controller
    controllers = self.get_controllers(flat_id)
  File "/config/custom_components/sauresha/sauresha.py", line 101, in get_controllers
    self._sensors = controllers
UnboundLocalError: local variable 'controllers' referenced before assignment

**Comment by volshebniks** [comment]
Какой период обновления стоит?

**Comment by Kirilloff73** [comment]
20 минут, пробовал увеличить до 60 - ни чего не изменилось. Помимо этого, удалял интеграцию и созданные сенсоры, а затем вновь установил, но это также не дало эффекта.

**Comment by volshebniks** [comment]
20 мало,  поставьте хотя бы 30 и подождите 1-2 часа. Если не будет обновляться будем разбираться.

**Comment by Kirilloff73** [comment]
Так и сделаю, понаблюдаю до завтра, потом отпишусь

**Comment by Kirilloff73** [comment]
Изменение периода на 30, а потом и на 60 ничего не дало.  Данные обновляются только при перезагрузке сервера.

**Comment by volshebniks** [comment]
выложите пожалуйста настройки  сенсоров.

должноы быть примерно так:
- platform: sauresha
  email: !secret saures_login
  password: !secret saures_pass
  flat_id: 9999
  counters_sn: 
      - 12371111
      - 12391111
  controllers_sn: 
      - 84FXXB10XXXE
  scan_interval:
       minutes: 30

**Comment by Kirilloff73** [comment]
- platform: sauresha 
  email: ! secret saures_login
  password: ! secret saures_pass
  flat_id: 10820 
  scan_interval: 
    minutes: 60 
  counters_sn: 
      - 41548615 
  controllers_sn: 
      - 84F3EB11043A
При этом на странице в личном кабиненте в закладке "контролеры" видно, что каждый час есть обращение к серверу

**Comment by Kirilloff73** [comment]
![Screenshot_20201123-165844_Home Assistant](https://user-images.githubusercontent.com/42699631/99970700-43803580-2dad-11eb-8aae-982aff2f4d2f.jpg)

**Comment by Kirilloff73** [comment]
могу предоставить доступ к системе, если это поможет

**Comment by Kirilloff73** [comment]
![20201123_172823](https://user-images.githubusercontent.com/42699631/99973806-3a916300-2db1-11eb-9572-e3ae6e0688e3.jpg)

**Comment by avbor** [comment]
Кол-во обращений к серверу означает сколько раз ваш контроллер связывался с облаком сауреса, это никоим образом не относится к ХА и этому компоненту.

**Comment by Kirilloff73** [comment]
Вчера обновил Ваш компонент, scan_interval увеличил до 90 но ситуация к сожалению не меняется. Сенсор самостоятельно не обновляется, обновленные данные подтягиваются  только при перезагрузке сервера.

**Comment by volshebniks** [comment]
А можете выдожить сюда значение сенсора со всем атрибутами после перезагрузки HA и его же, но часа через 3?

**Comment by Kirilloff73** [comment]
Сегодня чудесным образом сенсор начал обновляться. В настройках scan_interval установил 60 и обновил HA до 0.118.4, после этого сенсор стал обновляться

**Comment by Kirilloff73** [comment]
Рано обрадовался, вчера перезагрузил сервер и датчик перестал обновляться.
![Screenshot_20201129-084400_Home Assistant](https://user-images.githubusercontent.com/42699631/100534367-11dcf380-321f-11eb-9df6-aed7661d1cd7.jpg)

**Comment by mite667** [comment]
Здравствуйте.
Таже самая проблема, данные счетчиков воды обновляются только при перезагрузке scan_interval стоит 60.
Было ли найдено какое-то решение за это время?

**Comment by volshebniks** [comment]
> Здравствуйте.
> Таже самая проблема, данные счетчиков воды обновляются только при перезагрузке scan_interval стоит 60.
> Было ли найдено какое-то решение за это время?

К сожалению, у меня данная проблема не повторяется, даже с учетными данными, человека у которого она есть.
В логе у Вас есть какие-нибудь ошибки?

**Comment by Kirilloff73** [comment]
Решил проблему вот такой автоматизацией
- alias: Обновление датчика saures
  trigger:
    platform: time_pattern
    minutes: 5
  action:
    service: homeassistant.update_entity
    entity_id: sensor.sauresha

**Comment by mite667** [comment]
> Решил проблему вот такой автоматизацией
> 
> * alias: Обновление датчика saures
>   trigger:
>   platform: time_pattern
>   minutes: 5
>   action:
>   service: homeassistant.update_entity
>   entity_id: sensor.sauresha

Недавно только проверил, автоматизация работает. Данные начали обновляться. Спасибо большое. 
А вообще мысли есть почему так происходит у некоторых, что не обновляются данные самостоятельно?

**Comment by volshebniks** [comment]
Добрый день!

Да с  такой автоматизацией конечно работает.
Просто странно - что у меня таких проблем вообще нет.
а можете попробовать - выключить автоматизацию и посмотреть  обновляются ли
в свойствах сенсоров - вот эти поля:
last_update_time: next_update_time: ?


сб, 30 янв. 2021 г. в 22:07, mite667 <notifications@github.com>:

**Comment by Kirilloff73** [comment]
Попробую. По результату отпишусь.
