### ISSUE TITLE
Возможность задавать собственное имя для создаваемых сущностей

### ISSUE THREAD

**Issue by andreypolyak** [volshebniks/sauresha#9]
Добрый день! Во-первых, хочу выразить большую благодарность за создание компонента!

Но есть один feature request к нему: сейчас компонент всегда создает сущности для счетчиков и контроллеров на основании их серийных номеров. И, если в конфиге, можно указать серийные номера из файла secrets, то при использовании созданных сущностей в автоматизациях или template сенсорах, приходится указывать серийные номера уже вне файла secrets.

Все это приводит к тому, что при попытке выложить свои конфиги HA в общий доступ (что достаточно распространено среди пользователей HA), всему миру также будут доступны серийники счетчиков и контроллеров.

На мой взгляд, было бы здорово добавить опциональную возможность переопределить имя создаваемой сущности в конфиге, например вот так:

```yaml
counters_sn:
  - sn: 123456
    name: cold_water
```

**Comment by volshebniks** [comment]
Все эти серийники без знания логина и пароля, не имеют никакого смысла.

Но, наверно  давать свои имена было бы удобно.

Как чуть чуть свободного времени появится сделаю.
будет как то так:
```python
 controllers:
    !secret contr:
      name: my1
 counters:
   !secret c1:
      name: cold_water
   !secret c2:
      name: hot_water

**Comment by volshebniks** [comment]
Добавил в версии 0.6.0. Обратите внимание - что сильно изменилась настройка компонента.
